### PR TITLE
Upgrade parking_lot

### PR DESCRIPTION
**Pull request by sfackler**

### CODE REVIEW

**Comment by Matthias247** [comment]
Makes sense. Thanks! A newer `lock-api` version of `0.3.2` is also out. Guess for that it should actually be changed to cover `^0.3`.

Now I also need to check why the CI build failed

**Comment by dekellum** [comment]
Resolution on CI failure, release for this?

**Comment by Matthias247** [comment]
@dekellum The CI issue was unrelated and is resolved. Is the other question whether/when this will be released? There had been a few other changes which were technically API breaking, so I was waiting a bit whether more such things will accumulate before the next release. But if someone needs it I can also release a 0.3

**Comment by dekellum** [comment]
Thanks for the explanation. Without CI badge, I wasn't sure if there was something more to do with the parking_lot upgrade. Also knowing that you plan a new MINOR release is helpful.  As I'm looking to make my own release based on this, I should probably wait for 0.3.0

**Comment by dekellum** [comment]
Its been 4 weeks. Now I'm also seeing parking_lot 0.9 and 0.10 duplicates show up.  Would you be willing to cut a new release soon?

**Pull request merged**
