### PR TITLE
WIP: Add block & unblock method to mpmc channel

### PR DESCRIPTION
**Pull request by jean-airoldie**
This might be too much of a edge case but I have a situation where I have to close & drain a channel completely before reopening it. Normally I would put a lock a lock on the channel `sender`, but I think it could be more efficient and convenient to provide the ability for the user to reopen a channel after it was closed.

A side effect of this is that `close` does not necessarily block the channel forever, this would depend on the use case of the user. This means that conceptually a stream from the channel won't necessarily last as long as the channel because the user might `close` & `open`.

Also, it might make more sense to name these methods `block` and `unblock` since `close` seems like its forever.

### CODE REVIEW

**Comment by jean-airoldie** [comment]
Might make more sense to keep the `close` method but add a separate `block` and `unblock` method. The `block` method would prevent the user from sending on the channel temporarily until it is `unblock`ed. The difference between `block` and `close` is that close wakes up all waiters with Poll::Ready(None), and `block` doesn't.

**Comment by Matthias247** [comment]
I just had a short peek on the description and haven't looked at any code yet. But nevertheless a short comment before you spend more time on this: I am actually not very inclined on offering something like that. I see the transition to a closed state as a one-way workflow and also as a guarantee. Things inside the implementation are based on the guarantee, and some users might rely on the guarantee too.

I think being able to close and to reopen streams adds some additional complexity and probably also challenges - that we might not even be aware of yet. And the amount of use-cases where this is important is probably minimal. 

I would rather explore on how those use-cases could be solved in another fashion - e.g. via composition. You already mentioned that an async Mutex around the stream could work. I guess also replacing the channel with a fresh one could work. But of course the coordination to do this on the sender as well as receiver side in coordinated fashion might be tricky.

**Comment by jean-airoldie** [comment]
>  I see the transition to a closed state as a one-way workflow and also as a guarantee. Things inside the implementation are based on the guarantee, and some users might rely on the guarantee too.

My initial description is outdated since my implementation does not violate this guarantee from what I understand. Essentially it allows the user to keep queuing sender waiters  but prevents recv waiters from receiving values that where pushed in the array after the channel was `blocked`. So from the sender's perspective its as if the channel is full. The receive only sees the channel as it was before it was blocked.

Now that I think about it `freeze` and `unfreeze` might be better names.

> You already mentioned that an async Mutex around the stream could work. I guess also replacing the channel with a fresh one could work. But of course the coordination to do this on the sender as well as receiver side in coordinated fashion might be tricky.

In my use case the sender and receiver are separate so the coordination is indeed tricky. The reason I'm not a fan of the `Mutex` is because of the extra overhead since its in a particularly hot region. Moreover the `Mutex` prevents queuing wakers altogether which is not ideal.

> And the amount of use-cases where this is important is probably minimal.

I tend to agree, but recently I've ran into a couple use case where this is useful. The general pattern is when you have a handle to communicates with a I/O driver that is fallible. For instance:

```rust
// We use the handle to queue messages to the driver. The purpose of this handle
// is to provide a stable way to send messages across connection restarts.
struct Handle {
  outgoing: Sender<Vec<u8>>,
}

// The driver is a future that sends the outgoing messages from the `Handle` to
// the peer via the `Connection`. The connection is automatically restarted if it crashes.
struct Driver {
  outgoing: Receiver<Vec<u8>>,
  conn: Option<Connection>,
}
```

Even if the connection dies it can be restarted without having to replace the channel, but you do need to drain its content.

**Comment by Matthias247** [comment]
Ah ok. I actually know that kind of use-case. I typically solved it in a slightly different fashion: Instead of using a Channel to communicate with the `Driver` task, I use the following 3 components:
- A buffer for outgoing messages (e.g. `VecDeque`), which is protected by a **synchronous** Mutex.
- A semaphore, which allows for admission control the the buffer (you e.g. have as many permits as messages fit into the buffer. Or as bytes fit into it)
- An event (e.g. `ManualResetEvent` - but a `Channel` works too) which signals the `Driver` to run if it's not yet doing anything

With that setup enqueuing from the `Handle` looks like:
- Acquire a permit from the semaphore (optional. If you don't need backpressure you can also skip it)
- Lock the Mutex. Place the outgoing message into the send queue. Maybe inspect whether the `Connection` is currently closed and fail fast.
- Unlock the Mutex and signal the connection task to run. That might have an optimization that it does not do much if it's already running

The `Driver` side looks like:
- Be parked and wait for an event
- When the event is signalled, lock the Mutex and take out all messages which need to get sent
- Send all messages. Since we've taken out all available at once, we might benefit from vectored IO.
- Once done sending go back to the first step 

In that scenario if the `Connection` fails I can simply take a lock on the `Mutex` and clean the send buffer in an atomic fashion. 

I think your mechanism with a `blocked/unblocked` Channel solves it slightly differently. I guess both approaches might have their merit.

**Comment by jean-airoldie** [comment]
Thanks, that's an interesting approach. I'll think about it.

**Comment by jean-airoldie** [comment]
I'll close this for now.

**Pull request closed without merging**
