### PR TITLE
Bump parking_lot to 0.12

### PR DESCRIPTION
**Pull request by paolobarbolini**

### CODE REVIEW

**Comment by paolobarbolini** [comment]
Can we get a new patch release out @Matthias247? tokio 1.17 has just been released with the parking_lot 0.12 update, and I'd love to avoid duplicate dependency versions in my projects.

**Comment by cynecx** [comment]
> Can we get a new patch release out @Matthias247? tokio 1.17 has just been released with the parking_lot 0.12 update, and I'd love to avoid duplicate dependency versions in my projects.

Ping :)

**Comment by djc** [comment]
@Matthias247 friendly ping?

**Comment by FinnRG** [comment]
@Matthias247 Ping?

**Comment by Matthias247** [comment]
This is done.

**Pull request merged**
